apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-storage
 labels:
   app: pv
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteMany","ReadWriteOnce"]
  hostPath:
    path: /temp/data