apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: ing
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx
  rules:
  - host: test.com
    http:
      paths:
      - backend:
          service:
            name: test-dep
            port:
              number: 80
        path: /test
        pathType: Prefix
status:
  loadBalancer: {}
