apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-db
  namespace: demo
spec:
  serviceName: "db"
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
        - name: db
          image: redis
