apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-dep
  name: test-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-dep
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80
        resources:
          requests:
            cpu: 2
            memory: "2Gi"
          limit:
            cpu: 3
            memory: "3Gi"
        env:
          - name: APP_COLOR_
            value: "green"
          - name: APP_COLOR_CONFIG
            valueFrom:
              configMapKeyRef:
                 name: configmap-test
                 key: APP_AGE_CONF
          - name: APP_COLOR_SECRET
            valueFrom:
              secretKeyRef:
                name:  secret-test
                key: APP_AGE_SEC

        envFrom:
          - configMapRef:
              name: configmap-test
          - secretRef:
              name:  secret-test


        resources: {}
status: {}
